import Head from 'next/head'

import Hero from '../../components/Hero'
import SecondDiv from '../../components/SecondDiv'
import ThirdDiv from '../../components/ThirdDiv'
import FourthDiv from '../../components/FourthDiv'
import FifthDiv from '../../components/FifthDiv'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <SecondDiv />
        <ThirdDiv />
        <FourthDiv />
        <FifthDiv />
      </main>
    </>
  )
}
